### ISSUE TITLE
PR: Decouple Listen host and app

### ISSUE THREAD

**Issue by frank-dspeed** [adamhalasz/diet#11]
for people that whant to run a single instance with support for lets say 5000+ domains its usefull to de couple the app name and from listen 

at present listen creats a new object for every domain

better would be to listen simply on a port and then do a array for domain.tld = appname

greetings

ps. it would only need smal modification of hosts.js and index.js so we add a option for the object/array that stores domain to app routing.

**Comment by frank-dspeed** [comment]
Maybe saw it wrong current system works well with current object circular model but will investigate in real world testing.
no investigation at present needed.

**Comment by adamhalasz** [comment]
Let me know when you have an updated on this. I'm not sure what do you mean at the moment.

**Comment by frank-dspeed** [comment]
Its about the fact that every domain attaches the function it runs i think when i have a applaction with lets say 30 routes and lets say 20 middlewares on 5000 domains then i would with the current structure get the complet 30 routes and 20 middlewares replicated over 5000 domain entrys did i see that wrong?

do you know what i mean?

and i tought it would be a better way to some how store applications in a object and then assign domains to it.

but i don't got time to realy benchmark or even obtain the memory usage at present because i got so less time i simply deployed the app 500x the response times are great because i have only 300 accesses per secund so each server does only handle one access per secund at present.

but i will try soon to switch my loadbalancers and route more traffic to the new instances then i will optain mem usage and all that.

So the Main Issu for this ticket is that i saw when i console.log the app object with it routes hosts and all it gets visual realy realy realy big with 5000 + domains
