### ISSUE TITLE
PLZ: Release Current Version 1.0

### ISSUE THREAD

**Issue by frank-dspeed** [adamhalasz/diet#14]
It would be nice if you find time to release this as version 1.0 also publish npm and also make a git tag for that version thx a lot for corperation.

**Comment by adamhalasz** [comment]
Hi Frank,

Thanks a lot for your fixes. I'm really busy these days. I updated the NPM repository - the new version is v0.9.10

http://npmjs.com/package/diet

Thanks,
Adam
