### ISSUE TITLE
New Test Cases Needed!

### ISSUE THREAD

**Issue by frank-dspeed** [adamhalasz/diet#17]
Following looks none working.

Creating domains in  a other app that listen on same port as the app befor

so we need following test to pass befor any thing gets done

app1 = server();
app1 = listen(80)
app1 = routes header or else
app1 = listen('testhost.com')
app1 = listen('host2.tld:80')
app1.listen('http://host3.tld')

app2.listen(80)
app2.header()
app2.listen('http://bla.com:80')

app3.listen('last.com')
app3.footer('any')
app3 = server();

**Comment by adamhalasz** [comment]
Please let me know if the new diet@0.9.12 fixes these for you.

**Comment by frank-dspeed** [comment]
ya this part works but your rewrite droped the functionalty for using .listen('localhost:999')

**Comment by adamhalasz** [comment]
Oh you mean it should work without using http or https and it should default to http if the protocol it’s not provided. :) I’ll fix this as soon as I will have some time.

**Comment by frank-dspeed** [comment]
did it already

**Comment by frank-dspeed** [comment]
closed by  pull #24 aka v0.9.13
