### ISSUE TITLE
Update github releases and tags

### ISSUE THREAD

**Issue by frank-dspeed** [adamhalasz/diet#25]
This Project falls behind consistent state if we don't update the tags and releases of this repository.  i would offer also my self to get added to this project as extra maintainer for faster reaction. as i use this code base in production.

Also a git repo for the framework homepage probally would be good the gh-pages branch don't looks like the current page this is also considered inconsistent.

**Comment by adamhalasz** [comment]
Hey Frank,

I agree, but I'm just simply too busy at the moment. I only have a very few hours to spend weekly on diet. 

There is actually a repository for the homepage:
https://github.com/adamhalasz/dietjs.com

I'm really glad you would like to help maintaing the project.

Thanks,
Adam
