### ISSUE TITLE
Lets us only use console.log if no silent mode as also fix to show console.error

### ISSUE THREAD

**Issue by frank-dspeed** [adamhalasz/diet#26]
I think we should add some debugging stuff there are some handy debugging infos we gain at present via console.log as also we get errors in the console.log thats not a good thing!!!!

we should change that console.log infos only get posted if not in silent mode as example we got in server a console.log for location none set right that should get console.error() so it gets logged in the right file and that 

all other console log msges should get dispatched only if none silent! so we should make a console.log function that only logs if none silent we call it diet_console()
the function should check if silent is not set and then dispatch console.log

i assign my self to this :dash:

**Comment by adamhalasz** [comment]
Any updates?

**Comment by frank-dspeed** [comment]
ya the update is integrate and use npm install debug it allows handy filter able logging.
you can do var debug = require('debug')('DIETJS::SERVER')
debug('What we normaly log to console')

when we start the app with DEBUG=DIETJS* we get this msg as also when we do DEBUG=DIETJS::SERVER then we would only get the server messages you probally get the idea.

**Comment by adamhalasz** [comment]
Hey @frank-dspeed yeah debug is nice! :) Did you made a middleware for diet or are you using it as a standalone module?

**Comment by frank-dspeed** [comment]
i use it nativ in debug because its i think a core dependency like in express it is also used in every middleware that is bigger and in express it self

**Comment by frank-dspeed** [comment]
we need to replace console.log in all files with it and like Server init and that.

**Comment by Nosthertus** [comment]
it could be something like this

```Javascript
var server = require('diet')({
    debug: 2  //Debug level
});
```

where debug is actually a level of importance.. so let's say `2` would debug the server initialization and all requested routes that are registrered.. 

```sh
diet-debug: GET /users
diet-debug: PUT /users/3
```

**Comment by frank-dspeed** [comment]
no thats to complex i am preparing a version where are only DIETJS::SERVER and DIETJS::CONTROLLER stuff more log level dont exists in current code

**Comment by frank-dspeed** [comment]
you use it like 
~~~
DEBUG=DIETJS node bin/www
DEBUG=* node bin/www
DEBUG=DIETJS::* node bin/www
DEBUG=DIETJS::SERVER node bin/www
DEBUG=DIETJS::CONTROLLER, DIETJS::SERVER node index.js
~~~

**Comment by frank-dspeed** [comment]
i think this can be closed and solved on application (diet app level) no need to investigate.
