### ISSUE TITLE
404 host not found in public server

### ISSUE THREAD

**Issue by Nosthertus** [adamhalasz/diet#29]
just exact what the title says.. i can access it by localhost.. but host cant be accessed through public ip.. even when ports are open for public..

**Comment by Nosthertus** [comment]
I have been diving in diet's core.. and i have found out that routes are not being defined for some reason when it comes to public request.. `app.routes` is never defined so the server returns `404 host not found` on all requests

**Comment by adamhalasz** [comment]
@Nosthertus what version of diet do you use?

**Comment by Nosthertus** [comment]
i use 0.9.28

**Comment by Nosthertus** [comment]
is this a bug?

**Comment by Nosthertus** [comment]
I have found out that setting ` app.listen('http://190.202.164.84:8000/')` which is my public ip.. the server can now be acceded from internet.. no idea why this happens.. i'm connected through router and i have all ports open for my local ip

**Comment by adamhalasz** [comment]
Hey @Nosthertus I'm glad you managed it. Not sure what happened on your end. If you still have questions regarding this please open a new issue. I'm closing this now

**Comment by Nosthertus** [comment]
I didn't have anymore problems about this..

The server was running on a local network and i have understood which ip the server should be acceded as.. this could be due to `http.createServer`

Anyways.. i have made a pull request in `adamhaslasz/diet-static pull#1`
