### ISSUE TITLE
Diet vs Express benchmark

### ISSUE THREAD

**Issue by ohenepee** [adamhalasz/diet#30]
It would be cool to see a DietJS vs ExpressJS benchmark to see some performance gaps

**Comment by mnzt** [comment]
*ahem*
http://dietjs.com/resources/comparison#
:smile:

**Comment by ohenepee** [comment]
Could you possibly point to me the performance benchmarks there?

**Comment by adamhalasz** [comment]
@ohenepee @mnzt there is no express vs diet benchmark yet. I will add one later next week.

**Comment by ohenepee** [comment]
Thanks @adamhalasz

**Comment by adamhalasz** [comment]
Hey sorry guys I'm having a very busy week but I will do it soon.

**Comment by adamhalasz** [comment]
Hey @ohenepee @mnzt here you go:
https://github.com/adamhalasz/diet/tree/master/benchmarks/load_testing
