### ISSUE TITLE
Add grouping route

### ISSUE THREAD

**Issue by Nosthertus** [adamhalasz/diet#32]
Could be a nice idea.. but what if there was a function that groups all methods in a single route?

for example:

``` Javascript
app.group('/books', function(method){
    method.get(function($){

    });

    method.post(function($){

    });

    method.put(function($){

    });

    method.delete(function($){

    });

    // Other methods too..
});
```

**Comment by adamhalasz** [comment]
Hey @Nosthertus pretty good idea!

**Comment by Nosthertus** [comment]
great.. i came up with this when i was developing `diet-raml-generator`

**Comment by mnzt** [comment]
Syntactically, I think promises would be a better option, example:
```
app.group('/books', function(method){
  
    method.on("get", function($){

    })
    .on("post", function($){

    })
    .on("put", function($){

    })
    .on("delete", function($){

    })
    // Other methods too..
});
```

**Comment by Nosthertus** [comment]
@mnzt that is also a good idea. there could also be a function to catch all methods at once

**Comment by frank-dspeed** [comment]
At present i group it like this:

I create out of diet.js a server framework to listen for many thousend apps and domains. for my usecase maybe you can use that infos:

i do for the main server a global.server = diet
then i create diffrent controller/app1

then in the main server i do server.controller('app1')

so app1 needs top be a js file that defines a normal dietjs app and use a costum name for the server object. like app1= require diet ()
now app1 header or other get routes can use app1.controller and server.controller methods to require its files in a consistent way.

so app1 is the complet app group that is complet configured when i now whant to use that for a domain i only need to do in the main server index.js where we started

app1.listen('protocol://rest')

i can repeat that many 1000 times or simply let app1-4 listen for diffrent groups of domains.

then you create middelware functions so you can reuse the methods in all your apps and combine them so to groups.

greetings.

**Comment by adamhalasz** [comment]
Hey guys, love this topic. I will add this feature in the upcoming `v1.0`.

The API will most probably be like this:

```js
var books = app.resource('/books')
books.post(function($){ ... })
books.put(function($){ ... })
books.get(function($){ ... })
books.delete(function($){ ... })
```

Which allows chaining as well as @mnzt mentioned:

```js
app.resource('/books')
      .put(function($){ ... })
      .post(function($){ ... })
      .get(function($){ ... })
      .delete(function($){ ... })
```

Kind Regards,
Adam

**Comment by adamhalasz** [comment]
@frank-dspeed can you share some code snippets for your implementation?

**Comment by Nosthertus** [comment]
i suppose `resource()` would be something new to add to the API, but either way the example looks very nice, and really glad this framework is close to hit 1.0

**Comment by frank-dspeed** [comment]
Ya need to find the example have at present to much un sorted codes but will ping you back on this and will always watch this repo for current state

**Comment by luisvinicius167** [comment]
I changed the source code and I implemented this for me, and it is working very well. 

```javascript
app.group('/api/v1').then( route => {
  route('get', '/home', $ => { $.end(`User Home`) });
  route('post', '/insert', $ =>{ $.end(`Insert an User`) });
});

app.group('/api/v2').then( route => {
  route('get', '/home', $ => { $.end(`User Home v2`) });
  route('get', '/contact', $ => { $.end(`User Contact v2`) });
});
```

**Comment by luisvinicius167** [comment]
I created a grouping route module for ```Diet.js```. For me, it's very useful: https://github.com/luisvinicius167/diet-group-router

**Comment by adamhalasz** [comment]
As of `0.13.0` grouping is supported with `app.resource(path)`. It works as described above in my previous comment.

```js
var book = app.resource('/book')
      book.post(function($){ ... })
      book.put(function($){ ... })
      book.get(function($){ ... })
      book.delete(function($){ ... })
```

You can also chain it as such:

```js
app.resource('/book')
      .post(function($){ ... })
      .put(function($){ ... })
      .get(function($){ ... })
      .delete(function($){ ... })
```

For reference check out the Resource Example:
https://github.com/adamhalasz/diet/blob/master/examples/resource/index.js

**Comment by Nosthertus** [comment]
should i send a pull request of this in diet docs? or are you planning to add this in the docs at some time?

**Comment by frank-dspeed** [comment]
@Noshertus you can open a issue to add that to the docs but i think it has no core priority
