### ISSUE TITLE
Cannot use URL Object in app.listen()

### ISSUE THREAD

**Issue by wlekin** [adamhalasz/diet#33]
I try to use URL Object in app.listen() but I got a 'cannot call split of undefined' error.
URL String is fine.

**Comment by clooth** [comment]
This is because the API documentation tells you that the host property is called `hostname` instead of `host`.

Use an URL object like this:

```{
  protocol: 'http:',
  port: 800,
  host: 'localhost'
}```

**Comment by wlekin** [comment]
thanks so much!

**Comment by wlekin** [comment]
btw, how to redirect all www to non-www ?

**Comment by adamhalasz** [comment]
@wlekin how about this?

```js
server()
   .listen('http://www.yourDomain.com')
   .missing(function($){ $.redirect(config.domain + $.url.pathname) })
```

**Comment by wlekin** [comment]
but this could be a infinite loop if it is a real 404?

**Comment by adamhalasz** [comment]
@wlekin well as a server developer the definition of a "404" is up to you. These should work without problems. Just do not redirect any `non-www` url's to the 'www' host and you should be fine.

**Comment by wlekin** [comment]
i give it a try, but without www is become a "404 host not found", it wont even trigger missing function.

**Comment by adamhalasz** [comment]
hmm, let me know how this works out
