### ISSUE TITLE
HTTP methods

### ISSUE THREAD

**Issue by Ahmad-Ibrahim** [adamhalasz/diet#4]
Supporting other HTTP methods like PUT, DELETE and PATCH

**Comment by RedactedProfile** [comment]
I'm actually a little shocked this isn't initially supported.. hmm..

**Comment by Ahmad-Ibrahim** [comment]
Is this project dead? is it still maintained? no answer for a whole 9 days!!

**Comment by adamhalasz** [comment]
Sorry for the late answer. I'm working on it!

**Comment by adamhalasz** [comment]
I didn't implement all http methods before because I didn't really needed them :) I updated the github repo with `v0.9.2` which has support for `options`, `patch`, `put`, `trace` and `delete` methods. I'll update the npm repo and the documentation soon as well.
