### ISSUE TITLE
Object.Observe is not anymore proposal for ES7 so depricated

### ISSUE THREAD

**Issue by frank-dspeed** [adamhalasz/diet#42]
Plz remove it from the code it is not considered to be used anymore. npm throws warning anyway maybe it dont got your attention :D 

greetings

**Comment by adamhalasz** [comment]
Hey @frank-dspeed,

As of v0.10.5 you shouldn't receive any errors. I replaced the Native Object.Observe with a module. I need a way to observe changes on the Server Instances do to stuff like this:
https://github.com/adamhalasz/diet/blob/master/examples/events/index.js

I will look for alternative solutions, but for now this just works :) Do you have a better suggestion for event tracking?

Thanks,
Adam

**Comment by frank-dspeed** [comment]
Thats not a future Request use Node 7 or Node 6+ and you will get the depricated warning

**Comment by frank-dspeed** [comment]
maybe do what i do and npm install with diffrent nodejs versions i use
docker run -t -v /path/to/diet:/app node:6.0 '/bin/bash -c "cd /app; npm install"'

**Comment by frank-dspeed** [comment]
The only way i see to make the object observe able is implamenting nativ getter and setter methods.

so we dont allow modification from the Object without using the getter setter methods.

we could create something like a universal method that adds getters and setter functions to any object that uses that and so we can pass to that a callback for onChange like your onAny.

**Comment by frank-dspeed** [comment]
I found the coders of Object.Observe

they suggested: For developers who have been experimenting with O.o and are seeking a transition path, consider using a polyfill such as MaxArt2501/object-observe or a wrapper library like polymer/observe-js.

**Comment by adamhalasz** [comment]
Just published a new version with the ES6 Proxy which replaces object.observe which should fix this.
