### ISSUE TITLE
Load test

### ISSUE THREAD

**Issue by kikwit** [adamhalasz/diet#48]
On [this page](http://dietjs.com/resources/comparison#comingsoon) it's said that

>Diet is significantly faster than Vanilla Node.js.

I've created a simple benchmark whose results you can [see here](https://github.com/kikwit/kikwit). Diet seems slower than Express in my tests.
Is there something I'm missing? 
I've also tried setting NODE_ENV to production but it didn't make any difference.

**Comment by adamhalasz** [comment]
hey @kikwit I did those benchmark a while ago with different versions of Diet and Node. It is outdated :S 

The newer versions of Node.js are much faster. On my latest benchmark Vanilla (v5.7.0) is faster than Diet (v0.10.2) and Express (v4.13.4), and Diet is a bit faster than Express.
https://github.com/adamhalasz/diet/tree/master/benchmarks/load_testing

So yeah I need to update Diet's homepage :P I'm just really busy with my work these days.

Interesting framework by the way! 👍

**Comment by bondowe** [comment]
Thanks @adamhalasz. I return the compliment. I've played with diet a lot, it looks promising.

Kikwit isn't ready for production and the documentation isn't great yet.
