### ISSUE TITLE
Support for other HTTP verbs?

### ISSUE THREAD

**Issue by kokujin** [adamhalasz/diet#51]
Would there be support for other HTTP verbs in the future? (PUT, PATCH e.t.c) Thanks

**Comment by adamhalasz** [comment]
Hey @kokujin 

Diet already supports `GET`, `POST`, `PUT`, `HEAD`, `DELETE`, `TRACE`, `OPTIONS` and `PATCH`.
http://dietjs.com/api/server

Thanks,
Adam

**Comment by kokujin** [comment]
Great!
