### ISSUE TITLE
Question: How can I disable listening on port 80?

### ISSUE THREAD

**Issue by jake-walker** [adamhalasz/diet#56]
Hi,

I my aim is to have multiple diet instances but spread across different files. For Example:
__File 1__
```
var server = require('diet');

var app = server();
app.listen("mydomain.co.uk");

app.get('/', function($){
  $.end('Hello World');
});
```

__File 2__
```
var server = require('diet');

var app = server();
app.listen("myseconddomain.co.uk");

app.get('/', function($){
  $.end('Hello World 2');
});
```

When I start the first file it works OK but when starting the other it errors:
```
Error: listen EADDRINUSE 0.0.0.0:80
    at Object.exports._errnoException (util.js:1008:11)
    at exports._exceptionWithHostPort (util.js:1031:20)
    at Server._listen2 (net.js:1253:14)
    at listen (net.js:1289:10)
    at net.js:1399:9
    at _combinedTickCallback (internal/process/next_tick.js:77:11)
    at process._tickDomainCallback (internal/process/next_tick.js:122:9)
    at Module.runMain (module.js:577:11)
    at run (bootstrap_node.js:352:7)
    at startup (bootstrap_node.js:144:9)
```
and when I go to my VPS IP it says `404 host not found`. So I'm guessing its not working because both files are trying to listen on port 80 to show `404 host not found`.

Please someone help.

Thanks in advance.

**Comment by adamhalasz** [comment]
Hi Jake! Please take a look at my answer on stackoverflow about to hosting multiple domains with node:

http://stackoverflow.com/a/25352594

You cannot listen on the same port with 2 separate node processes with Diet (and not sure if you can do this with anything else either, although it would be possible)

Kind Regards,
Adam

**Comment by Nosthertus** [comment]
what is your OS?

**Comment by jake-walker** [comment]
Thanks @adamhalasz that's very helpful :)

**Comment by jake-walker** [comment]
@Nosthertus Linux - Ubuntu 15.04

**Comment by adamhalasz** [comment]
@jake-walker I'm glad I was able to help you! Let me know if you have any other questions.

Thanks,
Adam

**Comment by Nosthertus** [comment]
@jake-walker on linux, port 80 is only available for `root` user

from what i can tell on the log you gave us, node is trying to host on that port. You could try to host your server with root privileges like this

```bash
$ sudo node server.js
```

**Comment by jake-walker** [comment]
@Nosthertus Yeah, I'm running it as root
