### ISSUE TITLE
Redirect all routes to reactjs/react-router with static files

### ISSUE THREAD

**Issue by marekkobida** [adamhalasz/diet#58]
I need to redirect all routes to reactjs/react-router. diet-static must work and custom routes too.

```
const fs = require("fs")
const url = require("url")
const path = require("path")

const diet = require("diet")

const server = diet()

server.listen("http://www.google.sk")

const experiment = require("diet-static")({
  path: server.path + "/public"
})

server.footer(experiment);

server.get("/", ($) => {
  let a = path.join(server.path, "public", "index.html")

  fs.readFile(a, (error, data) => {
    $.header("Content-Type", "text/html")
    $.send(data)
    $.end()
  })
})
```

`server.get("*", ($) => {})` does not work with diet-static

**Comment by Nosthertus** [comment]
Greetings @marekkobida 

i am trying to understand the purpose of your question, i have little knowledge on react so i will try to help you from the server perspective

none of your routes won't work if you are loading `diet-static` in the footer (Please check Footer section in the API website [here](http://www.dietjs.com/api/server#app.footer)). Basically what `diet-static` does is handling the URL request and search for a file from the specified path, it returns 404 in case if the requested file is not found

So.. in other words, `diet-static` is overwriting your route logic, meaning that `server.get("*", ($) => {})` won't work with `diet-static`

**Comment by marekkobida** [comment]
Hi @Nosthertus 

Is this the right way how could I do this?

```
/* files.anything.sk */

const files = diet()

files.listen("http://files.anything.sk")

const experiment = require("diet-static")({
  path: path.join(files.path, "public", "files.anything.sk")
})

files.footer(experiment)

/* anything.sk */

const anything = diet()

anything.listen("http://anything.sk")

anything.get("/*", ($) => {

})
```

**Comment by Nosthertus** [comment]
Hi @marekkobida Sorry for the late answer

Does `react-router` support `HTML5` URL on your page?.. meaning that all URLs must be redirected to index without losing the requested url..

if that's the case.. then we have to tell the static server to always go to `index.html` for all requested URLs, as long as they are not requesting assets files like `JavaScript` and `Cascade Style` files..

```HTTP
http://myserver.com -> index.html
http://myserver.com/some/other/path -> index.html
http://myserver.com/dist/css/style.css -> dist/css/style.css
http://myserver.com/dist/js/app.js -> dist/js/app.js
```

so for achieving this behavior on Diet, we don't have to use `diet-static` module, for the reason i explained above.. we could just make our own footer logic

```JavaScript
var diet = require("diet");
var path = require("path");
var fs   = require("fs");
var mime = require("mime"); // I recommend using mime for telling the browser what kind of media file is recieving

var app = diet();

var staticDir = "path/to/static";
var indexFile = "static/index.html";

app.listen(80);

app.footer(($) => {
	// Get the requested uri path
	var uri = $.url.pathname;

	var extension = path.extname(uri);

	// Check if the requested uri path has exention (css, js) 
	// In case the extension was found and it's one of the above, send the requested file
	if(extension && (extension == ".css" || extension == ".js")){
		$.header("Content-Type", mime.lookup(uri));

		fs.readFile(path.join(staticDir, uri), (err, data) => {
			if(err){
				$.status(404, "File not found");
				$.end();

				throw error;
				$.return();
			}

			else{
				$.end(data);
				$.return();
			}
		});
	}

	// In case the extension was not found, or extension is not one of the above, send only the index file
	else{
		$.header("Content-Type", mime.lookup(indexFile));

		fs.readFile(path.join(staticDir, indexFile), (err, data) => {
			if(err){
				$.status(404, "File not found");
				$.end();

				throw error;
				$.return();
			}

			else{
				$.end(data);
				$.return();
			}
		});
	}
});
```

with this code, the server will always send index file, as long as the requested file is not `Cascade Style` or `JavaScript`.

Although this could be a nice feature to add this kind of behavior to static module, what do you think @adamhalasz ?.. i know i did not use the streaming way like i did on my module, but this way was the fastest i could write

**Comment by marekkobida** [comment]
Hi @Nosthertus 

_You are my hero! Thank you very much._

**Comment by Nosthertus** [comment]
Hey @marekkobida 

Glad i was able to help you
