### ISSUE TITLE
deprecated object.observe@0.2.6: Object.observe isn't an ES7 proposal anymore and will be removed from V8 - don't use it for production code

### ISSUE THREAD

**Issue by garylogin** [adamhalasz/diet#60]
Hi 
ran: npm install diet --save

diet@0.10.8

 deprecated object.observe@0.2.6: Object.observe isn't an ES7 proposal anymore and will be removed from V8 - don't use it for production code

what should i do?
Thanks

**Comment by adamhalasz** [comment]
Hey @garylogin . That's just a warning meaning future versions of node will not support Object.observe. It does not affect your code anyway you are fine safe! 

As for me I'll have to use a different way to observe events in the next releases of diet.

Thanks,
Adam

**Comment by KingPixil** [comment]
Yes I was wondering the same thing, I will be using Diet in production code.

I really don't want to use anything else since I :heart: diet. Please fix this :smile:

**Comment by Nosthertus** [comment]
i wonder for what purposes are you using `object observer` i think the best alternative would be defining `getters` and `setters`

**Comment by frank-dspeed** [comment]
@garylogin this is dublicate of #42 please close

**Comment by adamhalasz** [comment]
Just published a new version with the ES6 Proxy which replaces object.observe which should fix this.
