### ISSUE TITLE
Proposal: Download file

### ISSUE THREAD

**Issue by ahmadibrahim-c** [adamhalasz/diet#67]
It will be great if you can provide a way to download file from a route to be something like that

``` javascript
$.download('path/to/file', 'file name', options)
```

**Comment by Nosthertus** [comment]
There is an example on how to recieve files from a request in the webpage. Although it would be nice as a separated module feature

**Comment by ahmadibrahim-c** [comment]
Hey @Nosthertus , can you give me a link to that example?

**Comment by Nosthertus** [comment]
Sure. You can see it in http://dietjs.com/tutorials/router#middleware

`formidable` is used to parse `multipart/form-data` which is `blob` type and gather all the files from the submit

**Comment by ahmadibrahim-c** [comment]
As far as I understand this shows how to upload file, what I'm looking for is a way for a user to **download** file when he opens a link, like when he opens a link lilke this `https://uploadsite.com/download/12341234` he can then download the file

**Comment by Nosthertus** [comment]
I was thinking to make that feature for the module i made `diet-static-stream` but i have gotten pretty busy.. for the moment you would have to read the file and send it in the response.

I have made an example about sending files to the client which could be helpful for you in this [comment](https://github.com/bayorigin/diet/issues/58#issuecomment-235393146)

**Comment by ahmadibrahim-c** [comment]
Thank you so much!!

**Comment by adamhalasz** [comment]
@ahmadibrahim-c $.download actually sounds cool 👍

**Comment by adamhalasz** [comment]
As of `v0.14.0` you can use `$.download(path, filename)` as such:
```js
// Register a route that downloads the /image.png as diet_logo.png
app.get('/', function($){
    $.download('./image.png', 'diet_logo.png')
})
```

For reference check out the simple Download Example:
https://github.com/adamhalasz/diet/tree/master/examples/download

**Comment by Nosthertus** [comment]
@adamhalasz does this set any special headers to the response?, also.. does this have support for auto `mime-type` detection?

**Comment by adamhalasz** [comment]
@Nosthertus Yes it sets the content-disposition header. Yes it does detect the mime type since it is using $.sendFile which uses the mime.lookup method from the mime module.

**Comment by Nosthertus** [comment]
@adamhalasz are the headers set after or before calling the download method?.. i ask because there are cases where custom `content-type` is to be set with a different value which might not exist in `mime` module

**Comment by adamhalasz** [comment]
@Nosthertus The content-type header is set in $.sendFile which is called within the $.download method. You can take a look:
https://github.com/adamhalasz/diet/blob/master/controllers/protocols/http/signal.js#L65

**Comment by ahmadibrahim-c** [comment]
Thanks man! I really needed that.
