### ISSUE TITLE
Couldn't serve a static html file

### ISSUE THREAD

**Issue by mckenzieja** [adamhalasz/diet#69]
After hours of struggling. I couldn't get it to serve a single static html file. Are we forced to use ect? Say I want to serve a single static html file and then later decide to use a renderer?

**Comment by adamhalasz** [comment]
Hi @mckenzieja Sorry for hear that. With the `fs` module and setting the `content-type` to `text/html` you should be able to do it pretty quickly. No you are not forced to use ECT there is even a Nunjucks example:
https://github.com/bayorigin/diet/tree/master/examples/nunjucks

### Serving a single Static HTML File

Assuming a folder structure like this:
```
/myProject
...index.html
...index.js
```

And having this in `index.js`
```js
// Require File System Module
var fs = require('fs')

// Require Diet
var server = require('../../index')

// Create Server Instance
var app = server()

// Listen on Port 8000
app.listen(8000)

// Register RouteHandler for "http://localhost:8000/"
app.get('/', function($){

	// set "Content-Type" header to "text/html"
	$.header('Content-Type', 'text/html')

	// Read file at ~/yourProject/index.html
    fs.readFile(__dirname+'/index.html',function(error, content){
    	// handle error
    	if(error) throw error;
    	
    	// Serve the file to the client
        $.end(content.toString())
    })
})
```

And this in `index.html`:
```html
<!DOCTYPE html>
<html>
    <head>
        <title>Hello world</title>
    </head>
    <body>
        <h1>Hello world</h1>
    </body>
</html>
```

#### References:
- fs.readFile() documentation: https://nodejs.org/api/fs.html#fs_fs_readfile_file_options_callback
- 14.11 Content-Encoding at https://www.w3.org/Protocols/rfc2616/rfc2616-sec14.html

**Comment by Nosthertus** [comment]
greetings, please let us know if @adamhalasz response was the solution to your problem

**Comment by mckenzieja** [comment]
Thanks for your prompt response! 

 
I've only had experience in Express. That being said, is it possible to use express say for routing but still use diet for virtual hosting? 

Here's what I have and it seems to work. I had it working before I saw your solution.  

```
var server = require('diet')

var app = server()



var ect = require('diet-ect')({ path: app.path+'/views/html/' })
var static = require('diet-static')({path: app.path+'/views/'})

app.listen('http://localhost:8000', function(){
  console.log("Server is Running");
})

app.header(ect, function($){  $.return(); })
app.footer(static)

//Homepage
app.get('/', function($){
  $.html()
})
```

**Comment by Nosthertus** [comment]
Not sure what you are trying to do, `diet-ect` is used to interpolate data from `nodejs` into `html` and then serves the files with the results, while `diet-static` just serves the files without interpolation.

You can use `diet` as virtual hosting for `express` but i wouldn't recommend it, cause `diet` is not yet that stable to handle it properly

**Comment by mckenzieja** [comment]
Well I'd like to interpolate data later. 

I tried your method but it displays the entire html content as a string in the browser.

**Comment by Nosthertus** [comment]
@adamhalasz method just loads the entire static file and sends it in the response as it is, without any interpolation

**Comment by mckenzieja** [comment]
Well the browser doesnt interpret the data. It just display raw html. Tags and all.

**Comment by Nosthertus** [comment]
I'm sorry for the late response, i am currently moving and i took a small time to answer.. can't you still show interpolated data?

**Comment by adamhalasz** [comment]
Hey @mckenzieja As of `v0.12.0` you can also use `$.sendFile(path)`

```
app.get('/', function($){
        $.sendFile('./index.html')
})
```

Check out the sendFile example for reference:
https://github.com/adamhalasz/diet/tree/master/examples/sendfile
