### ISSUE TITLE
What is the future of this?

### ISSUE THREAD

**Issue by Ahmad-Ibrahim** [adamhalasz/diet#7]
I really like this framework and want to use it for production after using it in some internal projects, is this gonna be maintained or it is just a hobby project?

**Comment by adamhalasz** [comment]
Hi Ahmad,

I'm happy to hear that! Yes I'm going to maintain it and I'm also here to help if you have a specific question. 

Cheers,
Adam

**Comment by Ahmad-Ibrahim** [comment]
I have no issues to be honest, great job man.. maybe I will ask for some new features later like routes grouping

**Comment by RedactedProfile** [comment]
Just remember @ahmed-ibrahim that Diet is intended to be as lean as possible, I would argue that the only thing this project should worry about is fixing any existing issues, improving performance further where possible, and keeping the framework up to standards with releases of node and io
