### ISSUE TITLE
Can I use Diet.js in Production?

### ISSUE THREAD

**Issue by luisvinicius167** [adamhalasz/diet#70]
I just question this because I liked the diet.js, but the last commit was six months ago and I have no idea about the maintenance for this project.

**Comment by Nosthertus** [comment]
You can use `diet.js` in production, keep in mind this module is not stable yet and future changes could damage your current code because of big `API` changes

**Comment by luisvinicius167** [comment]
Ok! Have any plans to launch the new version of diet.js? Have a branch of that API changes?

**Comment by Nosthertus** [comment]
Unfortunately. There won't be any updates for a while. BayOrigin's CEO is busy with the company startup

**Comment by adamhalasz** [comment]
@luisvinicius167 Sorry for the late reply. Yes you can use it in production. The API hasn't changed much in the last few years and there are no plans to drastically change it in the future. We might add new features but every change is going to be documented.

@Nosthertus Thanks for helping out with the issues! But wait why do you think diet is not stable?

**Comment by Nosthertus** [comment]
@adamhalasz there are some features that are not properly working, i have created issues for them, and i think it's better to point the package on not being stable stage until it reaches `v1.0.0`, for the time being i will see diet as `alpha` and of course i will still help with this repository cause `Diet` is actually the only `node.js` hosting package i like

**Comment by adamhalasz** [comment]
@Nosthertus Thanks for your kind words. I understand that there are some rare bugs, I will fix then soon. The stability of a module has not much to do with the version. The version is more important in compatibility matters when new features/methods are added. 

@luisvinicius167 I have websites running for years under diet with 100% uptime. Diet is production ready and I will keep making it better :)
