### ISSUE TITLE
how to debug?

### ISSUE THREAD

**Issue by askie** [adamhalasz/diet#71]
I change the code of controller file home.js:
`$.data.title = 'Hello World 123444'`

but when I refresh the page of http://192.168.0.108:8000/

the page nothing changed,
but where restart node, refresh the page is changed.

how to debug diet?

**Comment by Nosthertus** [comment]
I don't clearly understand the issue. Please add more detail of your problem

**Comment by askie** [comment]
I start diet app at http://192.168.0.108:8000/ using method:
`node index.js`

and then using sublime to edit the file controller/homg.js:
` module.exports.display = function($){
        $.data.title = '222'
        $.end()
    }`

then I refresh the page of http://192.168.0.108:8000/,
nothing changed, the $.data.title still is the last value,


but when I ctr+c stop the node,and run `node index.js` again,
the page http://192.168.0.108:8000/ title is 222,

so diet cache the home.js when start?
how to dynamic edit any files to debug ?

**Comment by Nosthertus** [comment]
I'm sorry. I'm still scratching my head about this issue.. could you post `index.js` and HomeController files?

**Comment by askie** [comment]
all file is using yo diet  created,
then run  node index.js
then open http://192.168.0.108:8000/
and then edit controller/home.js
and then refresh http://192.168.0.108:8000/ ,nothing changed

ctr+c 
and then run node index.js
the page http://192.168.0.108:8000/ changed!

**Comment by askie** [comment]
[index.js.zip](https://github.com/adamhalasz/diet/files/792076/index.js.zip)
[home.js.zip](https://github.com/adamhalasz/diet/files/792077/home.js.zip)

**Comment by Nosthertus** [comment]
So you are chaning the content of the server files while the server is on?

**Comment by askie** [comment]
yes

**Comment by Nosthertus** [comment]
Now i see what is happening.. when `node.js` execution starts, the program loads the whole code including the files that are required and then the logic execution starts.. unfortunately `node.js` is unable to update the content on the memory when a file is changed.

So in other words. If you want to apply changes to `node.js` you must restart `node`.

There are node modules that can restart the program automatically for any change detected

**Comment by askie** [comment]
where app is developing, this is very necessary to dynamic loading the changed file.
I find a solution :  npm install supervisor -g
and then run: supervisor index.js 
well done!

thx!

**Comment by Nosthertus** [comment]
I don't know any other reason than developing for restarting the server for changes on the server files.. but if this helped you then i'm glad i was able to help.

If there is no other problem then please close this issue

Keep in mind that github issues are for bugs and errors found in the related repository. You can use `stackoverflow` for any other kind of problems
