### ISSUE TITLE
Diet.js on Heroku

### ISSUE THREAD

**Issue by luisvinicius167** [adamhalasz/diet#73]
```javascript
const server = require('diet')
const app = server()

require('diet-group-router')(app);
require('./routes')(app);

app.listen(process.env.PORT || 5000)
```

I don't know why this not run on Heroku.

**Comment by Nosthertus** [comment]
does the server give any response?

**Comment by luisvinicius167** [comment]
Yeah! But, heroku logs show:

`HTTP Server is listening on http://0.0.0.0:8080/`
`Error R10 (Boot timeout) -> Web process failed to bind to $PORT within 60 seconds of launch`
 
```
at=error code=H10 desc="App crashed" method=GET path="/" host=restdb.herokuapp.com 
request_id=52d4e846-b23d-4c1d-8aaa-1f3efc120ad8 fwd="179.197.231.87" dyno= connect= service= status=503 by
tes=
```

**Comment by Nosthertus** [comment]
i'm not sure, but it could be a server error rather than diet

**Comment by luisvinicius167** [comment]
Try yourself to put some application with diet.js on heroku. It's hard man! :P

**Comment by adamhalasz** [comment]
@luisvinicius167 Make sure you use a newer node version (>= v6.4.0) You can specify the node version in your package.json:

https://devcenter.heroku.com/articles/nodejs-support#specifying-a-node-js-version

```js
"engines": {
    "node": "v7.3.0"
},
```

**Comment by adamhalasz** [comment]
But unfortunately you are most probably going to get a "404 host not found". Heroku is confusing around the hostnames & ports. It registers the app to a local port but it sends port 80 and a different hostname in the HTTP headers when you access the app URL. 

I will try to come up with a solution.

**Comment by luisvinicius167** [comment]
Yeah. I got the same problem on xervo.io, host not found.

**Comment by Nosthertus** [comment]
that was actually the issue i was thinking.. this also happens when incoming connections are forwarded on `linux` using `iptables`.. diet does not know that the incoming connection is actually the connection that should work so it returns `404 host not found`

**Comment by adamhalasz** [comment]
@luisvinicius167 I have a quick fix that should work with the current version:
```js
app.hosts['YOUR_HEROKU_HOSTNAME:80'] = app
```

So for example if your hostname is `fathomless-meadow-25269.herokuapp.com` then this should work for you:
```js
const server = require('diet')
const app = server()

require('diet-group-router')(app);
require('./routes')(app);

app.listen(process.env.PORT || 5000)
app.hosts['fathomless-meadow-25269.herokuapp.com:80'] = app
```

**Comment by adamhalasz** [comment]
@luisvinicius167 as of `v0.15.0` you will be able to use `app.host(location)` as such:

```js
// listen on a port
app.listen(process.env.PORT || 5000)

// accept a hostname
app.host('yourdomain.com')
```

This is a demo app that I made on Heroku to test this:
[https://fathomless-meadow-25269.herokuapp.com/](https://fathomless-meadow-25269.herokuapp.com/)

The source code behind it:

```js
const server = require('diet')
const app = server()

app.get('/', function($){
	$.end('Hello Heroku from Diet!')
})

app.listen(process.env.PORT || 5000)
app.host('fathomless-meadow-25269.herokuapp.com')
```

Hope this helps! Let me know if you have any other questions :)

**Comment by luisvinicius167** [comment]
@adamhalasz nice! Working now ;)

**Comment by adamhalasz** [comment]
@luisvinicius167 I'm glad to hear that it works!
