### ISSUE TITLE
Abandonware?

### ISSUE THREAD

**Issue by xeno** [adamhalasz/diet#77]
Really would like to use Diet, but I'm worried the project has been abandoned. With 4 PRs open since October and no new issues in months -- is anyone still here?

**Comment by oscarr-reyes** [comment]
sadly this might be abandoned, owner is the only one to accept PR for the repository

**Comment by grantcarthew** [comment]
@adamhalasz is still active on github. Adam, add some maintainers!

**Comment by josephtveter** [comment]
@adamhalasz add some maintainers. I like the idea of this but I would like it slightly more robust. I am willing to do the footwork and submit some PRs. If you are not going to maintain it please add some maintainers.

**Comment by adamhalasz** [comment]
If anyone is still interesting in maintenance please let me know!
