### ISSUE TITLE
Mustache + diet.js

### ISSUE THREAD

**Issue by andreaslacza** [adamhalasz/diet#78]
Hey,
is it possible to use my **own** or the **mustachejs** template engine

with diet like in express:
http://expressjs.com/en/advanced/developing-template-engines.html

**Comment by frank-dspeed** [comment]
@andreaslacza https://github.com/adamhalasz/diet/issues/37 look into this

**Comment by cutejs** [comment]
You can do it, but the only example is Adam's own diet-ect module, so you'll have to base yours on that.
