### ISSUE TITLE
Diet + OpenShift

### ISSUE THREAD

**Issue by lukehedger** [adamhalasz/diet#9]
Trying to get a simple Diet server running on OpenShift (free plan) but the server never starts (runs fine locally). The page itself (http://diet-levelout.rhcloud.com/) returns a 503 and the logs throw:

```
http://dietjs.com/
 ... HTTP Server is listening on http://127.5.35.1:8080
{ protocol: 'http:',
  slashes: true,
  auth: null,
  host: '10.225.25.124:8080',
  port: '8080',
  hostname: '10.225.25.124',
  hash: null,
  search: null,
  query: null,
  pathname: '/',
  path: '/',
  href: 'http://10.225.25.124:8080/' }
events.js:72
	throw er; // Unhandled 'error' event
              ^
Error: listen EACCES
    at errnoException (net.js:901:11)
    at Server._listen2 (net.js:1020:19)
    at listen (net.js:1061:10)
    at Server.listen (net.js:1135:5)
    at App.listen (/var/lib/openshift/558a6ec9e0b8cd5c870000e2/app-root/runtime/repo/node_modules/diet/models/server.js:19:35)
    at Object.<anonymous> (/var/lib/openshift/558a6ec9e0b8cd5c870000e2/app-root/runtime/repo/server.js:8:5)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
DEBUG: Program node server.js exited with code 8
```

Here's the code:

```
var server = require('diet'),
    app = server();

var server_ip_address = process.env.OPENSHIFT_NODEJS_IP || '127.0.0.1';
var server_port = process.env.OPENSHIFT_NODEJS_PORT || 3000;

app.listen('http://' + server_ip_address + ':' + server_port);

console.log(app.location);

app.get('/', function ($) {
  $.end('Hello World!');
});
```

The server runs with the default example and a simple Express :hear_no_evil: app but not the above.

Any ideas?

**Comment by adamhalasz** [comment]
```
Error: listen EACCES
```

This error happens when you don't the operating system doesn't grant access for your app to handle a specific port or ip. The default IP used by diet is '0.0.0.0' which is a generic IP that allows diet to listen on multiple domains/addresses. 

I'm trying to figure out a good solution that allows you to change the IP in the listen method while still allowing to listen on multiple domains with a single Server Instance.

**Comment by frank-dspeed** [comment]
I think my fix can help here to he can listen simply on 0.0.0.0 or a single port and can still get requests that arnt explicit have ip:port in request.headers.host

greetings.

**Comment by frank-dspeed** [comment]
if he listens on a other ip and or host combo we can modify the fix to simply default the first hosts[1] entry

then it don't matters where he listens on it checks if it gets explicit routes for that host if not defaults to the first diet js listen app.

**Comment by frank-dspeed** [comment]
can be closed i runned this even on open shift it was a user fail probably the fail was that he don't knowed that open shift don’t opens ports on the box they use a external load balancer that does the forwarding
